networks:
  backend:
    driver: bridge

services:
  db:
    image: postgres:17
    restart: unless-stopped
    networks:
      - backend
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    env_file:
      - .env
    volumes:
      - postgres_data_windows:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  redis:
    image: redis:alpine
    container_name: backend_redis_windows
    restart: unless-stopped
    command: ["redis-server", "--appendonly", "yes"]
    networks:
      - backend
    ports:
      - "6381:6379"
    volumes:
      - redis_data_windows:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  alembic:
    build: .
    command: sh ./run_migrations.sh
    networks:
      - backend
    environment:
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_HOST: db
      DB_PORT: 5432
      MODE: ${MODE}
      ALGORITHM: ${ALGORITHM}
      SECRET_KEY: ${SECRET_KEY}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      MNEMONIC: ${MNEMONIC}
      TRON_API_KEY: ${TRON_API_KEY}
      ENCRYPTION_KEY: ${ENCRYPTION_KEY}
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./migrations:/app/migrations
      - ./run_migrations.sh:/app/run_migrations.sh

volumes:
  postgres_data_windows:
  redis_data_windows:

