from alembic import op

import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2025_08_19_0000'
down_revision = '2025_08_18_0000'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('wallet_address', sa.String(length=34), nullable=True))
    op.create_unique_constraint('uq_user_wallet_address', 'user', ['wallet_address'])
    
    op.create_table('nonce',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('address', sa.String(length=34), nullable=False),
        sa.Column('nonce', sa.String(length=255), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('used', sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nonce_address'), 'nonce', ['address'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_nonce_address'), table_name='nonce')
    op.drop_table('nonce')
    op.drop_constraint('uq_user_wallet_address', 'user', type_='unique')
    op.drop_column('user', 'wallet_address')
    # ### end Alembic commands ###
