"""add transaction model

Revision ID: 2ecf387d9e4c
Revises: 2025_08_20_0000
Create Date: 2025-09-19 01:54:33.258465

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2ecf387d9e4c'
down_revision: Union[str, Sequence[str], None] = '2025_08_20_0000'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.DECIMAL(), nullable=False),
    sa.Column('status', sa.Enum('created', 'broadcasted', 'pending', 'confirmed', 'failed', 'dropped', name='transactionstatus'), nullable=False),
    sa.Column('type', sa.Enum('outgoing', 'incoming', name='transactiontype'), nullable=False),
    sa.Column('user_wallet_address', sa.String(length=42), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_wallet_address'], ['wallet.address'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('game_room', sa.Column('players', sa.Integer(), nullable=False, server_default='0'))
    op.alter_column('nonce', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('nonce', 'used',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.add_column('user', sa.Column('username', sa.String(length=255), nullable=False, server_default=''))
    op.alter_column('user', 'total_winnings',
               existing_type=sa.INTEGER(),
               type_=sa.DECIMAL(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'total_winnings',
               existing_type=sa.DECIMAL(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('user', 'username')
    op.alter_column('nonce', 'used',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('nonce', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_column('game_room', 'players')
    op.drop_table('transaction')
    # ### end Alembic commands ###
