"""initial commit

Revision ID: 2f1e25e6bd00
Revises: 
Create Date: 2025-07-09 03:56:14.549241

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f1e25e6bd00'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_room',
    sa.Column('room_id', sa.UUID(), nullable=False),
    sa.Column('entry_fee', sa.Integer(), nullable=False),
    sa.Column('min_players', sa.Integer(), nullable=False),
    sa.Column('max_players', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('room_id')
    )
    op.create_index(op.f('ix_game_room_room_id'), 'game_room', ['room_id'], unique=False)
    op.create_table('user',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('wallets', sa.JSON(), nullable=False),
    sa.Column('primary_wallet_id', sa.String(length=50), nullable=True),
    sa.Column('balance', sa.DECIMAL(), nullable=False),
    sa.Column('games_played', sa.Integer(), nullable=False),
    sa.Column('total_winnings', sa.Integer(), nullable=False),
    sa.Column('leaderboard_rank', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_user_user_id'), 'user', ['user_id'], unique=False)
    op.create_table('game_session',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('room_id', sa.UUID(), nullable=False),
    sa.Column('total_bank', sa.DECIMAL(), nullable=False),
    sa.Column('zone_fund', sa.Integer(), nullable=False),
    sa.Column('bonus_fund', sa.Integer(), nullable=False),
    sa.Column('current_phase', sa.String(length=20), nullable=False),
    sa.Column('next_shrink_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['game_room.room_id'], ),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_index(op.f('ix_game_session_session_id'), 'game_session', ['session_id'], unique=False)
    op.create_table('wallet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('address', sa.String(length=42), nullable=False),
    sa.Column('network', sa.String(length=10), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('address')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wallet')
    op.drop_index(op.f('ix_game_session_session_id'), table_name='game_session')
    op.drop_table('game_session')
    op.drop_index(op.f('ix_user_user_id'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_game_room_room_id'), table_name='game_room')
    op.drop_table('game_room')
    # ### end Alembic commands ###
